services:
  tickrate-demo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "../app/public:/usr/src/app/public:ro"
    restart: unless-stopped
